const MALE_FIRST_NAMES = [
  "Aarav", "Vivaan", "Aditya", "Vihaan", "Arjun", "Sai", "Reyansh", "Ayaan",
"Krishna", "Ishaan", "Shaurya", "Atharv", "Advik", "Pranav", "Kabir", "Rudra",
"Rahul", "Amit", "Suresh", "Rajesh", "Vikram", "Sanjay", "Deepak", "Manoj",
"Rohan", "Karan", "Varun", "Rohit", "Ankit", "Nikhil", "Akash", "Abhishek",
"Ansh", "Anshul", "Aryan", "Arnav", "Aadi", "Aarush", "Aayush", "Abhinav",
"Abhimanyu", "Abhay", "Abeer", "Advay", "Agastya", "Ahan", "Akhil", "Akshay",
"Alok", "Amar", "Amay", "Aman", "Amol", "Anand", "Anirudh", "Anirban",
"Anuj", "Anup", "Anurag", "Armaan", "Arpit", "Arvind", "Ashish", "Ashok",
"Ashwin", "Atul", "Avinash", "Ayush", "Bharat", "Bhavesh", "Bhanu", "Bhuvan",
"Chandan", "Chetan", "Chirag", "Darshan", "Dev", "Devaansh", "Devansh", "Devendra",
"Dhruv", "Dheeraj", "Dhanush", "Dilip", "Divyansh", "Eshan", "Gaurav", "Girish",
"Govind", "Harsh", "Harshit", "Harshvardhan", "Himanshu", "Hriday", "Ivaan", "Jai",
"Jatin", "Jay", "Jayant", "Jignesh", "Kailash", "Kartik", "Kartikeya", "Keshav",
"Kunal", "Laksh", "Lakshay", "Lalit", "Lokesh", "Madhav", "Mahesh", "Manav",
"Manish", "Mayank", "Mihir", "Mohit", "Mukesh", "Nakul", "Naman", "Naveen",
"Navin", "Neel", "Neeraj", "Nishant", "Nitin", "Om", "Omkar", "Pankaj",
"Parth", "Parthiv", "Piyush", "Pradeep", "Prakash", "Pranav", "Pratham", "Pratik",
"Prem", "Raghav", "Raghavendra", "Raj", "Rajat", "Rajeev", "Rajiv", "Rakesh",
"Ramesh", "Ranbir", "Ranjit", "Ravi", "Ravindra", "Rishabh", "Rishi", "Ritesh",
"Rituraj", "Ronit", "Roshan", "Sachin", "Sagar", "Sahil", "Sameer", "Samarth",
"Samir", "Sandeep", "Sarthak", "Sarvesh", "Shailesh", "Shiv", "Shivam", "Shivansh",
"Shlok", "Shrey", "Shreyansh", "Shubham", "Siddharth", "Siddhant", "Sohan", "Soham",
"Somesh", "Sourabh", "Sourav", "Suraj", "Surya", "Tanish", "Tanishq", "Tarun",
"Tejas", "Uday", "Ujjwal", "Utkarsh", "Vaibhav", "Varad", "Ved", "Vedant",
"Veer", "Venkatesh", "Vijay", "Vineet", "Vinit", "Vishal", "Vishesh", "Vivek",
"Yash", "Yashwant", "Yatin", "Yuvraj", "Zaid", "Zayan", "Aariv", "Aariz",
"Abeer", "Adit", "Adwait", "Agnivesh", "Akhilesh", "Alokesh", "Amrit", "Anay",
"Angad", "Aniket", "Ankit", "Anmol", "Anshuman", "Arhaan", "Arjit", "Arjun",
"Arnav", "Arun", "Arush", "Ashutosh", "Atharva", "Avyan", "Ayansh", "Brijesh",
"Chaitanya", "Chirantan", "Daksh", "Dakshesh", "Darsh", "Devraj", "Dhanraj", "Dhaval",
"Digvijay", "Dinesh", "Divit", "Durgesh", "Eklavya", "Faizan", "Fardeen", "Farhan",
"Gagan", "Gautam", "Girish", "Gokul", "Gopal", "Gyan", "Hardik", "Hari",
"Harish", "Hemant", "Hitesh", "Inder", "Indrajeet", "Ishwar", "Jagat", "Jagdish",
"Janak", "Jaspreet", "Javed", "Jayesh", "Jeevan", "Kamal", "Kanishk", "Kapil",
"Karanveer", "Kartik", "Kaushal", "Kavin", "Kedar", "Keshav", "Khushal", "Kishan",
"Kishore", "Krish", "Krishiv", "Kshitij", "Kumar", "Kunwar", "Laxman", "Madan",
"Mahavir", "Manan", "Manav", "Mandar", "Mangesh", "Manthan", "Mayur", "Mukul",
"Mukund", "Nakul", "Nandan", "Nandish", "Narendra", "Narayana", "Naresh", "Naveen",
"Navneet", "Neer", "Nihal", "Nilesh", "Nirav", "Nirbhay", "Nirmal", "Nishit",
"Nitesh", "Niranjan", "Ojas", "Omendra", "Pankaj", "Parag", "Paras", "Pavan",
"Prabhat", "Prakash", "Pranesh", "Prateek", "Pratyush", "Pravin", "Priyansh", "Pulkit",
"Rachit", "Raghu", "Raghunath", "Rahul", "Rajendra", "Rajesh", "Rajnish", "Rajat",
"Rakesh", "Raman", "Ramesh", "Ranjeet", "Ranveer", "Ratan", "Ratnesh", "Ravish",
"Ravikant", "Raghav", "Rehan", "Rishan", "Rishit", "Ritesh", "Rituraj", "Rohin",
"Ronav", "Rudransh", "Rupesh", "Sachin", "Sahil", "Samar", "Samay", "Samarjeet",
"Sameer", "Sanket", "Sankalp", "Sarthak", "Satish", "Satyam", "Satyendra", "Saurabh",
"Saurav", "Shankar", "Shantanu", "Sharad", "Shashank", "Shekhar", "Shivendra", "Shivraj",
"Shreyas", "Shubhan", "Shubh", "Siddhesh", "Sikandar", "Sohan", "Sohil", "Somnath",
"Sonu", "Sparsh", "Srihan", "Srinivas", "Subhash", "Sudhir", "Sujal", "Sukesh",
"Sumit", "Sunil", "Surendra", "Suresh", "Swapnil", "Tapan", "Tapas", "Tej",
"Tejas", "Tushar", "Umesh", "Upendra", "Utpal", "Vansh", "Varad", "Vardhan",
"Vasu", "Vatsal", "Vedansh", "Veeransh", "Vibhor", "Vicky", "Vidhur", "Vijendra",
"Vikas", "Vikrant", "Vimal", "Vinay", "Vinod", "Vipul", "Viraj", "Viren",
"Virendra", "Vishnu", "Vishwas", "Vivan", "Vivekanand", "Yashas", "Yashraj", "Yogesh",
"Yuvansh", "Yuvan", "Zoravar", "Abeer", "Adit", "Advaith", "Agnik", "Ahan",
"Akarsh", "Akshat", "Amey", "Amogh", "Anvay", "Arhaan", "Arush", "Atharv",
"Avik", "Avinash", "Ayushman", "Bhuvik", "Bodhi", "Devanshu", "Devit", "Dhairya",
"Dhruv", "Ekansh", "Harshil", "Hridhaan", "Ivaan", "Jash", "Jashan", "Jatin",
"Kairav", "Kairav", "Kiaan", "Kiaan", "Kriday", "Krishang", "Lakshya", "Luv",
"Maan", "Manas", "Moksh", "Naksh", "Naitik", "Nivaan", "Nivansh", "Ojas",
"Parv", "Pradyumn", "Pranshu", "Riaan", "Rian", "Ronav", "Rudraksh", "Saanvi",
"Samarth", "Shivay", "Shreyans", "Taarush", "Taksh", "Tavish", "Tushit", "Vayun",
"Vedik", "Viresh", "Vivan", "Yuvaan", "Aaryan", "Aaryav", "Aariv", "Aarush",
"Abhir", "Abhiraj", "Abhiraaj", "Abhishek", "Adarsh", "Adesh", "Ainesh", "Ajay",
"Ajit", "Amod", "Anant", "Anirvan", "Anshraj", "Arav", "Arindam", "Arunesh",
"Ashray", "Avdesh", "Balraj", "Balram", "Bhargav", "Bhuvanesh", "Chirayu", "Darpan",
"Darshil", "Devesh", "Dhairav", "Dhrupad", "Eshwar", "Gaurang", "Girish", "Harin",
"Harendra", "Harshad", "Indrajeet", "Jairaj", "Jitesh", "Kush", "Kushal", "Lohit",
"Mahendra", "Manendra", "Mitesh", "Nagesh", "Nandan", "Naveen", "Nirmit", "Pritam",
"Rachit", "Ragav", "Rajveer", "Rishabh", "Rohit", "Rudra", "Samar", "Sanjay",
"Saransh", "Shail", "Shashwat", "Shivanshu", "Siddhant", "Smit", "Srijan", "Sudarshan",
"Suryaansh", "Tanmay", "Tarak", "Tavish", "Utsav", "Vansh", "Varun", "Vatsal",
"Vihan", "Vijay", "Vikram", "Virat", "Vishant", "Yatin", "Yogendra", "Yuvraj"
];

const FEMALE_FIRST_NAMES = [
"Ananya", "Aadhya", "Diya", "Myra", "Saanvi", "Anika", "Navya", "Ira",
"Kiara", "Pari", "Riya", "Meera", "Kavya", "Ishita", "Priya", "Neha",
"Pooja", "Sunita", "Anjali", "Kavita", "Sneha", "Nisha", "Rekha", "Geeta",
"Aaradhya", "Aarohi", "Aanya", "Aashi", "Aashvi", "Aditi", "Ahana", "Akshara",
"Alisha", "Amaya", "Amrita", "Anaya", "Anushka", "Anvi", "Aradhana", "Aria",
"Arushi", "Asha", "Ashika", "Asmita", "Avani", "Avika", "Avni", "Ayana",
"Bhavya", "Bhumika", "Charvi", "Chhavi", "Damini", "Darshika", "Devika", "Dhriti",
"Diya", "Disha", "Divya", "Drishti", "Eesha", "Eshita", "Gauri", "Gayatri",
"Grishma", "Hansa", "Harini", "Harshita", "Hema", "Himani", "Ishani", "Ishika",
"Jahnavi", "Janhvi", "Jasmin", "Jaya", "Jhanvi", "Juhi", "Kajal", "Kalyani",
"Kamya", "Kanchan", "Kareena", "Karishma", "Kashish", "Kashvi", "Kavisha", "Keerthi",
"Khushi", "Kirti", "Komal", "Kritika", "Kumud", "Kusum", "Lakshmi", "Lavanya",
"Leela", "Lipi", "Madhavi", "Mahi", "Mahima", "Maira", "Malavika", "Malini",
"Manisha", "Manya", "Meenal", "Mitali", "Mrunal", "Muskan", "Naina", "Namrata",
"Nandini", "Nandita", "Nargis", "Natasha", "Navika", "Neelam", "Nidhi", "Nikita",
"Nilam", "Nimisha", "Niharika", "Nirali", "Nivedita", "Noor", "Ojasvi", "Palak",
"Pallavi", "Pankhuri", "Parineeta", "Payal", "Pihu", "Poonam", "Pragya", "Pranjal",
"Prarthana", "Pratibha", "Preeti", "Prema", "Priyanka", "Radhika", "Ragini", "Raina",
"Rajni", "Raksha", "Rashi", "Rashmi", "Rasika", "Raveena", "Reema", "Reena",
"Renu", "Rhea", "Riddhi", "Ritika", "Ritu", "Riya", "Roshni", "Ruhi",
"Rupali", "Sakshi", "Saloni", "Samaira", "Samiksha", "Sana", "Sanaya", "Sanjana",
"Sapna", "Sara", "Sarika", "Sarita", "Saumya", "Shagun", "Shalini", "Shanaya",
"Shikha", "Shilpa", "Shivani", "Shivanya", "Shraddha", "Shreya", "Shriya", "Shruti",
"Simran", "Smita", "Smriti", "Snehal", "Sonali", "Sonam", "Sonia", "Srishti",
"Supriya", "Swara", "Swati", "Tanya", "Tanisha", "Tanuja", "Tara", "Trisha",
"Uma", "Urvi", "Vaidehi", "Vaishali", "Vamika", "Vani", "Varsha", "Vedika",
"Veena", "Vidhi", "Vidhya", "Vijaya", "Vini", "Vinita", "Yamini", "Yashika",
"Yashvi", "Yuvika", "Zara", "Zoya", "Aarini", "Aarna", "Aarvi", "Aarya",
"Aashika", "Aayushi", "Abha", "Abhilasha", "Adhira", "Advika", "Aesha", "Aishani",
"Aishwarya", "Akanksha", "Akshita", "Alka", "Amisha", "Amrita", "Anamika", "Anam",
"Anchal", "Anindita", "Anisha", "Anjali", "Ankita", "Anmol", "Anshika", "Antara",
"Anuradha", "Anushree", "Apoorva", "Archana", "Arpita", "Arti", "Arya", "Ayesha",
"Bani", "Barkha", "Beena", "Bharti", "Bhavana", "Bina", "Bindu", "Brinda",
"Chaitali", "Chandni", "Charita", "Charu", "Chitra", "Damini", "Deepa", "Deepali",
"Deepika", "Deepti", "Devanshi", "Diksha", "Dimple", "Dipali", "Dipika", "Esha",
"Ekta", "Elina", "Garima", "Gitanjali", "Gulika", "Hiral", "Ila", "Indira",
"Indu", "Ipsita", "Jagruti", "Janki", "Jasleen", "Jaya", "Jyoti", "Kajal",
"Kalpana", "Kangana", "Kanupriya", "Karuna", "Kashvi", "Kavita", "Kiran", "Kishori",
"Kripa", "Krishna", "Kritika", "Kuhu", "Kumari", "Kusum", "Lalita", "Lata",
"Latika", "Laxmi", "Madhuri", "Madhu", "Madhulika", "Mahak", "Mansi", "Manvi",
"Mayra", "Megha", "Mehak", "Mekhala", "Minal", "Mira", "Misha", "Mithila",
"Monika", "Mona", "Mridula", "Namisha", "Nandita", "Nandini", "Neelima", "Neetu",
"Neha", "Niharika", "Nisha", "Nishtha", "Nitya", "Niyati", "Nupur", "Padmini",
"Parul", "Pavani", "Pavitra", "Poonam", "Prabha", "Pragati", "Pranavi", "Pratima",
"Prerna", "Preeti", "Priyal", "Priyasha", "Rachana", "Rachita", "Radha", "Rajeshwari",
"Ranjana", "Rashika", "Rashmi", "Raveena", "Ravina", "Reena", "Renuka", "Richa",
"Riddhima", "Rimjhim", "Rina", "Rinku", "Roshika", "Ruchi", "Ruchika", "Rupika",
"Sabina", "Sadhana", "Sakina", "Salma", "Samaira", "Samantha", "Sameera", "Samreen",
"Sana", "Sandhya", "Sangita", "Sanjana", "Sanjukta", "Sanya", "Saranya", "Sarina",
"Seema", "Shaila", "Shailja", "Shanvi", "Sharanya", "Sharmila", "Shefali", "Sheetal",
"Shilpi", "Shivangi", "Shivika", "Shobha", "Shona", "Shravya", "Shreya", "Shubhangi",
"Shweta", "Sia", "Sonal", "Sonali", "Soumya", "Suhani", "Sukanya", "Suman",
"Sunaina", "Sunita", "Supriya", "Surabhi", "Sushma", "Swara", "Swati", "Tanu",
"Tanvi", "Tanya", "Tejaswini", "Tina", "Tulika", "Tulsi", "Uma", "Urmi",
"Urvashi", "Vaani", "Vaishnavi", "Vandana", "Varsha", "Vasudha", "Veda", "Vedanshi",
"Veena", "Vibha", "Vibhuti", "Vidya", "Vijeta", "Vimala", "Vineeta", "Vinisha",
"Vishakha", "Vrinda", "Yamini", "Yashasvi", "Yashika", "Yogita", "Zeenat", "Zoya",
"Aadhira", "Aahana", "Aakriti", "Aarika", "Aarushi", "Aashna", "Aastha", "Aavya",
"Abhaya", "Abhiruchi", "Adrija", "Advaita", "Ahalya", "Ahilya", "Aishani", "Akriti",
"Alina", "Alisha", "Amaira", "Amisha", "Amrita", "Anahita", "Anaya", "Angel",
"Anushri", "Anvita", "Aparna", "Apurva", "Arpana", "Arshiya", "Aruhi", "Aryahi",
"Ashima", "Ashwini", "Atisha", "Avisha", "Ayushi", "Bhumika", "Chandrika", "Charitha",
"Chinmayi", "Damayanti", "Darpana", "Devanshi", "Dhanvi", "Dhwani", "Eshani", "Eshwari",
"Ganga", "Hansika", "Harshika", "Heena", "Hetal", "Ishwari", "Jivika", "Kaira",
"Kairavi", "Kashvi", "Kavina", "Kavya", "Khyati", "Krisha", "Krishika", "Lisha",
"Madhavi", "Madhura", "Mahira", "Manasvi", "Manya", "Medha", "Moksha", "Naina",
"Navika", "Nayra", "Niharika", "Nimisha", "Nitya", "Oviya", "Pallavi", "Prisha",
"Raina", "Ranya", "Rashi", "Riddhima", "Ritika", "Ruhani", "Saanika", "Samaira",
"Samaira", "Sanika", "Sharvi", "Shivanya", "Shreya", "Siya", "Suhana", "Tanishka",
"Tanushree", "Trisha", "Vanya", "Vanya", "Vrishti", "Yashvi", "Yuvika", "Zara"
];

const LAST_NAMES = [
"Sharma", "Verma", "Gupta", "Singh", "Kumar", "Patel", "Reddy", "Iyer",
"Nair", "Joshi", "Mehta", "Agarwal", "Malhotra", "Chopra", "Kapoor", "Bansal",
"Yadav", "Mishra", "Pandey", "Thakur", "Rao", "Desai", "Kulkarni", "Menon",
"Saxena", "Tiwari", "Dubey", "Srivastava", "Bhatia", "Chauhan", "Arora", "Sethi",
"Khanna", "Shah", "Jain", "Goyal", "Mittal", "Goel", "Aggarwal", "Singhal",
"Jindal", "Khandelwal", "Maheshwari", "Gupta", "Bhardwaj", "Bhatt", "Tripathi", "Shukla",
"Vajpayee", "Dwivedi", "Chaturvedi", "Pathak", "Pandit", "Mishra", "Upadhyay", "Trivedi",
"Shukla", "Srivastava", "Sinha", "Prasad", "Jha", "Choudhary", "Choudhury", "Rathore",
"Rajput", "Solanki", "Sisodia", "Rathod", "Parmar", "Prajapati", "Patil", "Jadhav",
"Deshmukh", "Pawar", "Shinde", "Gaikwad", "More", "Kadam", "Chavan", "Bhosale",
"Salunkhe", "Sawant", "Mane", "Gavli", "Dhumal", "Lokhande", "Wagh", "Suryawanshi",
"Naik", "Nayak", "Shetty", "Bhat", "Hegde", "Gowda", "Reddy", "Naidu",
"Raju", "Rao", "Varma", "Murthy", "Krishnan", "Pillai", "Menon", "Nambiar",
"Panicker", "Warrier", "Kurup", "Nair", "Pillai", "Madhavan", "Iyer", "Iyengar",
"Shastri", "Subramanian", "Srinivasan", "Venkatesh", "Venkataraman", "Raman", "Ramakrishnan", "Narayanan",
"Krishnamurthy", "Chandrasekar", "Balakrishnan", "Rajagopal", "Sundaram", "Swaminathan", "Viswanathan", "Gopal",
"Acharya", "Bhatta", "Bhat", "Kashyap", "Dixit", "Joshi", "Purohit", "Vyas",
"Oza", "Dave", "Bhatt", "Pandya", "Patel", "Shah", "Mehta", "Modi",
"Parekh", "Dalal", "Vora", "Doshi", "Soni", "Zaveri", "Merchant", "Mistry",
"Contractor", "Engineer", "Sanghvi", "Thakkar", "Desai", "Trivedi", "Bhatt", "Gandhi",
"Kapadia", "Choksi", "Adani", "Amin", "Dholakia", "Vakil", "Nanavati", "Ruparel",
"Jhaveri", "Kothari", "Lodha", "Bajaj", "Goenka", "Birla", "Agarwal", "Bansal",
"Mittal", "Singhania", "Jindal", "Dalmia", "Poddar", "Mahajan", "Tandon", "Sachdeva",
"Anand", "Bedi", "Suri", "Wadhwa", "Wadhawan", "Ahuja", "Oberoi", "Chawla",
"Bhalla", "Sood", "Gulati", "Kohli", "Puri", "Puri", "Mehra", "Trehan",
"Vohra", "Arora", "Batra", "Sethi", "Khurana", "Juneja", "Aneja", "Talwar",
"Sabharwal", "Chadha", "Grover", "Nanda", "Bhasin", "Madan", "Miglani", "Sarin",
"Sharma", "Verma", "Yadav", "Jatav", "Gurjar", "Gujjar", "Meena", "Mina",
"Rana", "Rawat", "Negi", "Bisht", "Kandari", "Bhandari", "Bisht", "Dhyani",
"Joshi", "Panwar", "Karki", "Bora", "Tiwari", "Thakur", "Chauhan", "Rana",
"Rathore", "Solanki", "Parmar", "Chavda", "Gohil", "Jadeja", "Zala", "Vaghela",
"Makwana", "Dabhi", "Dodia", "Gadhvi", "Barot", "Rabari", "Darbar", "Thakor",
"Patil", "Jadhav", "Pawar", "Shinde", "Chavan", "More", "Kadam", "Mane",
"Gaikwad", "Bhosale", "Deshmukh", "Salve", "Sawant", "Naik", "Shirke", "Ghorpade",
"Ingale", "Kamble", "Waghmare", "Jagtap", "Mhatre", "Mohite", "Koli", "Borkar",
"Thombre", "Sable", "Darekar", "Shinde", "Pansare", "Khot", "Dhere", "Gawande",
"Reddy", "Naidu", "Raju", "Rao", "Goud", "Gowda", "Shetty", "Hegde",
"Bhat", "Acharya", "Kamath", "Pai", "Shenoy", "Prabhu", "Nayak", "Poojary",
"Adiga", "Bhandary", "Kundar", "Mallya", "Udupa", "Rai", "Mokashi", "Kulkarni",
"Deshpande", "Joshi", "Gokhale", "Apte", "Ranade", "Phadke", "Bhide", "Karmarkar",
"Limaye", "Lele", "Datar", "Ketkar", "Gadgil", "Kelkar", "Agashe", "Karve",
"Modak", "Sane", "Vaidya", "Godbole", "Kale", "Dandekar", "Paranjape", "Sahasrabuddhe",
"Shirodkar", "Karnik", "Bapat", "Bhagwat", "Damle", "Desai", "Patwardhan", "Sathe",
"Banerjee", "Chatterjee", "Mukherjee", "Ganguly", "Ghosh", "Bose", "Das", "Dutta",
"Datta", "Sen", "Sengupta", "Bhattacharya", "Chakraborty", "Roy", "Basu", "Sarkar",
"Majumdar", "Mitra", "Nandi", "Saha", "Pal", "Paul", "Ganguly", "Lahiri",
"Guha", "Bhowmik", "Ghoshal", "Bhattacharjee", "Chakrabarti", "Bandyopadhyay", "Ray", "De",
"Dasgupta", "Banerji", "Mukherji", "Barman", "Bhowal", "Mondal", "Biswas", "Adhikari",
"Pradhan", "Mohanty", "Panda", "Patnaik", "Behera", "Nayak", "Mishra", "Rout",
"Das", "Sahu", "Jena", "Sahoo", "Samal", "Barik", "Nanda", "Pattnaik",
"Mahapatra", "Acharya", "Tripathy", "Dhal", "Swain", "Nayak", "Maharana", "Lenka",
"Reddy", "Rao", "Naidu", "Chowdary", "Choudary", "Varma", "Konda", "Kapu",
"Komati", "Setty", "Shetty", "Gowda", "Hegde", "Bhat", "Rai", "Acharya",
"Menon", "Nair", "Pillai", "Kurian", "Thomas", "George", "Mathew", "Joseph",
"Varghese", "Abraham", "Philip", "John", "Paul", "Jacob", "Samuel", "David",
"Fernandes", "D'Souza", "D'Silva", "Rodrigues", "Pereira", "Gomes", "Dias", "Costa",
"Almeida", "Menezes", "Noronha", "Lobo", "Rebello", "Furtado", "Correia", "DeSouza",
"Shaikh", "Khan", "Ansari", "Qureshi", "Siddiqui", "Pathan", "Mirza", "Syed",
"Sheikh", "Malik", "Mughal", "Hussain", "Ahmed", "Ali", "Beg", "Baig",
"Farooqui", "Rizvi", "Naqvi", "Kazmi", "Hashmi", "Usmani", "Abbasi", "Chishti",
"Dar", "Bhat", "Wani", "Lone", "Mir", "Koul", "Kaul", "Pandita",
"Raina", "Handoo", "Razdan", "Mattoo", "Bhat", "Sopori", "Bakshi", "Dhar",
"Singh", "Kaur", "Gill", "Sandhu", "Sidhu", "Brar", "Mann", "Grewal",
"Dhillon", "Cheema", "Aulakh", "Bajwa", "Randhawa", "Chahal", "Toor", "Sohal",
"Bhullar", "Sekhon", "Johal", "Deol", "Bains", "Dosanjh", "Pannu", "Virk",
"Atwal", "Tiwana", "Heer", "Walia", "Sodhi", "Chadha", "Kapoor", "Arora",
"Thakur", "Karki", "Rawat", "Bhandari", "Joshi", "Bisht", "Negi", "Rautela",
"Semwal", "Nautiyal", "Uniyal", "Dabral", "Purohit", "Bhatt", "Pandey", "Tiwari",
"Jha", "Sah", "Sahu", "Mandal", "Paswan", "Kushwaha", "Maurya", "Koeri",
"Kurmi", "Lodhi", "Saini", "Khatik", "Gurjar", "Meena", "Jatav", "Dhobi",
"Rajbhar", "Nishad", "Bind", "Mallah", "Yadav", "Ahir", "Gaderia", "Kushwaha",
"Chaudhary", "Choudhary", "Dahiya", "Deswal", "Dalal", "Ahlawat", "Sangwan", "Sheoran",
"Phogat", "Dagar", "Beniwal", "Poonia", "Jakhar", "Godara", "Dhaka", "Kadian",
"Rathi", "Khatri", "Saini", "Duggal", "Monga", "Sachdeva", "Arora", "Batra"
];

const AGE_OPTIONS = ["< 50 years", "> 50 years"];
const YES_NO_OPTIONS = ["Yes", "No"];

const CLINICAL_CONDITIONS = [
  "Diabetes",
  "High Blood pressure",
  "High Cholesterol",
  "Anaemic",
];

const DISORDERS = [
  "Liver disease",
  "Kidney disease",
  "Endocrine disease  (e.g.Thyroid disease)",
];

function pickOne(items) {
  return items[Math.floor(Math.random() * items.length)];
}

function pickSome(items) {
  const count = Math.floor(Math.random() * (items.length + 1));
  const shuffled = [...items].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

/** ~90% Male, ~10% Female */
export function pickWeightedGender() {
  return Math.random() < 0.9 ? "Male" : "Female";
}

export function generateRandomIndianName(gender = pickWeightedGender()) {
  const firstNames = gender === "Male" ? MALE_FIRST_NAMES : FEMALE_FIRST_NAMES;
  return `${pickOne(firstNames)} ${pickOne(LAST_NAMES)}`;
}

export function generateRandomAnswers(gender = pickWeightedGender()) {
  return {
    age: pickOne(AGE_OPTIONS),
    gender,
    swellingBothLegs: pickOne(YES_NO_OPTIONS),
    swellingWorseEvening: pickOne(YES_NO_OPTIONS),
    swellingAllOverBody: pickOne(YES_NO_OPTIONS),
    swellingFaceMorning: pickOne(YES_NO_OPTIONS),
    breathingDifficulty: pickOne(YES_NO_OPTIONS),
    breathingDifficultyLying: pickOne(YES_NO_OPTIONS),
    breathingDifficultyWalking: pickOne(YES_NO_OPTIONS),
    clinicalConditions: pickSome(CLINICAL_CONDITIONS),
    disorders: pickSome(DISORDERS),
  };
}
